version: "3.8"

services:
  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  client-app:
    build:
      context: ./ClientApp
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
